# Generated by Django 5.1.3 on 2025-04-14 12:44

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('faculty', models.CharField(choices=[('Faculty of Engineering', 'Faculty of Engineering'), ('Faculty of Science', 'Faculty of Science'), ('Faculty of Social Science', 'Faculty of Social Science'), ('Faculty of Arts', 'Faculty of Arts'), ('Faculty of Basic Science', 'Faculty of Basic Science'), ('Faculty of Law', 'Faculty of Law')], max_length=50)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(max_length=500, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='journals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
