# Generated by Django 5.1.3 on 2025-03-24 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('faculty', models.CharField(choices=[('Faculty of Engineering', 'Faculty of Engineering'), ('Faculty of Science', 'Faculty of Science'), ('Faculty of SocialScience', 'Faculty of SocialScience'), ('Faculty of Arts', 'Faculty of Arts'), ('Faculty of Basic Science', 'Faculty of Basic Science'), ('Faculty of Law', 'Faculty of Law')], max_length=50)),
                ('description', models.TextField()),
                ('abstract', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='journals/')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
