# Generated by Django 5.1.3 on 2025-03-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='description',
        ),
        migrations.AlterField(
            model_name='journal',
            name='faculty',
            field=models.CharField(choices=[('Faculty of Engineering', 'Faculty of Engineering'), ('Faculty of Science', 'Faculty of Science'), ('Faculty of Social Science', 'Faculty of Social Science'), ('Faculty of Arts', 'Faculty of Arts'), ('Faculty of Basic Science', 'Faculty of Basic Science'), ('Faculty of Law', 'Faculty of Law')], max_length=50),
        ),
    ]
